export const THEMES = {
    emerald: {
      id: 'emerald',
      name: 'Smeraldo',
      description: 'Il tema operativo di default. Verde neon su nero profondo.',
      minLevel: 1,
      accent: '#00FF88',
      accentHSL: '155 100% 50%',
      gradient: 'from-emerald-500 to-green-400',
      bgGlow: 'rgba(0, 255, 136, 0.15)',
      icon: '💎',
    },
    ruby: {
      id: 'ruby',
      name: 'Rubino',
      description: 'Rosso fuoco. Per operatori con almeno Livello 2.',
      minLevel: 2,
      accent: '#FF3366',
      accentHSL: '345 100% 60%',
      gradient: 'from-red-500 to-pink-400',
      bgGlow: 'rgba(255, 51, 102, 0.15)',
      icon: '🔴',
    },
    amethyst: {
      id: 'amethyst',
      name: 'Ametista',
      description: 'Viola profondo. Sblocca al Livello 4.',
      minLevel: 4,
      accent: '#A855F7',
      accentHSL: '270 95% 65%',
      gradient: 'from-purple-500 to-violet-400',
      bgGlow: 'rgba(168, 85, 247, 0.15)',
      icon: '🟣',
    },
    solar: {
      id: 'solar',
      name: 'Solare',
      description: 'Oro e ambra. Sblocca al Livello 6.',
      minLevel: 6,
      accent: '#FBBF24',
      accentHSL: '45 96% 56%',
      gradient: 'from-amber-400 to-yellow-300',
      bgGlow: 'rgba(251, 191, 36, 0.15)',
      icon: '☀️',
    },
    arctic: {
      id: 'arctic',
      name: 'Artico',
      description: 'Blu ghiaccio. Sblocca al Livello 8.',
      minLevel: 8,
      accent: '#38BDF8',
      accentHSL: '198 93% 60%',
      gradient: 'from-sky-400 to-cyan-300',
      bgGlow: 'rgba(56, 189, 248, 0.15)',
      icon: '❄️',
    },
  };